# default-constants.toml
# A list of defaults to use for any homelab-related machine

default-username = "saphnet-user"
authorized-keys = [ # Try to rotate these every now and then...
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHYjHkLEoqnhIg91FVA32nL7qbJe2l+Iy+t/WX98z7td hihacks@valk-pc", # Directly via personal computers
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICBb79Z1HFfgBM2XVyURzsXRG0b0fJRNplyN3v80CF8j hihacks@crummytop"
]
timezone = "America/Los_Angeles"

[networking]
gateway = "192.168.8.1"
nameservers = ["8.8.8.8", "8.8.4.4", "1.1.1.1"]

[email]
address = "homelab@saphnet.xyz"
host = "mail.privateemail.com"
port = "465"