# instance-values.toml
# A list of values to use to instantiate docker-host for docker-host-pve3

hostname = "docker-host-pve3"
domain = "int-net.saphnet.xyz"

[networking]
ip-address = "192.168.8.232" # docker-host-pve3.int-net.saphnet.xyz
ip-prefix-length = 24 # 192.168.8.0/24
interface = "ens18"
