# instance-values.toml
# A list of values to use to instantiate docker-host for docker-host-pve1

hostname = "docker-host-pve1"
domain = "int-net.saphnet.xyz"

[networking]
ip-address = "192.168.8.116" # docker-host-pve1.int-net.saphnet.xyz
ip-prefix-length = 23 # 192.168.8.0/23
interface = "ens18"
