# version-lock.toml
# Used to lock various versions, like Docker images in Compose files to specific tagged versions

state-version = "25.05" # https://nixos.wiki/wiki/FAQ/When_do_I_update_stateVersion