# instance-values.toml
# A list of values to use to instantiate the main Komodo/Ansible control server

hostname = "control-server"
domain = "int-net.saphnet.xyz"

[networking]
ip-address = "192.168.8.211" # control-server.int-net.saphnet.xyz
ip-prefix-length = 24 # 192.168.8.0/24
interface = "ens18"
